joint_limits:
  head_pan:
    has_velocity_limits: true
    max_velocity: 10000
    has_acceleration_limits: true
    max_acceleration: 2000
  left_w2:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: true
    max_acceleration: 0.8
  right_s1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.3
  left_w1:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: true
    max_acceleration: 0.8
  left_e0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.3
  right_w1:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: true
    max_acceleration: 0.8
  right_w2:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: true
    max_acceleration: 0.8
  left_s0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.3
  right_s0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.3
  right_e1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.3
  left_s1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.3
  right_e0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.3
  right_w0:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: true
    max_acceleration: 0.8
  left_e1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.3
  left_w0:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: true
    max_acceleration: 0.8